// Code generated by ifacemaker; DO NOT EDIT.

package http

import (
	"context"
)

// Server ...
type Server interface {
	// Start starts the HTTP server.
	Start()
	// Stop stops the HTTP server.
	Stop(ctx context.Context)
}
