// Code generated by ifacemaker; DO NOT EDIT.

package github

import (
	"context"
)

// Client ...
type Client interface {
	// GetStars returns the list of repositories starred by the user.
	GetStars(ctx context.Context) <-chan *StarredRepository
}
