// Code generated by go-simpler.org/sloggen. DO NOT EDIT.

package slogx

import "log/slog"
import "time"

func Component(value string) slog.Attr       { return slog.String("component", value) }
func Duration(value time.Duration) slog.Attr { return slog.Duration("duration", value) }
func Err(value error) slog.Attr              { return slog.Any("err", value) }
