// Code generated by ifacemaker; DO NOT EDIT.

package engine

import (
	"context"

	"github.com/blevesearch/bleve/v2"
)

// Engine ...
type Engine interface {
	// BatchIndex indexes the given data in batches of the given size.
	BatchIndex(data []Indexable, batchSize int) error
	// Search executes the given query and returns the results.
	// TODO: if we want to sort by starredAt, we need to index it as a date field and use sort https://blevesearch.com/docs/Sorting/
	Search(ctx context.Context, q string, from int, size int, fields ...string) (*bleve.SearchResult, error)
}
